### ISSUE TITLE
getting error while running the command

### ISSUE THREAD

**Issue by premhunt** [zewish/php-postfix-maillog-importer#2]
Hi ,

I am trying to use the command and getting this error:
PHP Warning:  PDO::quote() expects parameter 1 to be string, object given in /home//script/phpmysqlparser/php-postfix-maillog-importer-master/maillogimporter/writer/mysql.php on line 85
PHP Fatal error:  Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not execute UPDATE database statement: "UPDATE `email_log` SET `date_updated` = , `status` = 'deferred', `info` = IF(`info` = "", 'connect to outllook.com[40.84.199.233]:25: Connection timed out' , CONCAT(`info`, "\n", 'connect to outllook.com[40.84.199.233]:25: Connection timed out')) WHERE `postfix_message_id` = 'B952F19FA96'"' in /home/script/phpmysqlparser/php-postfix-maillog-importer-master/maillogimporter/writer/mysql.php:95
Stack trace:
#0 /home/script/phpmysqlparser/php-postfix-maillog-importer-master/maillogimporter/writer/mysql.php(78): MaillogImporter\Writer\MySql->_updateEmailData('B952F19FA96', Object(DateTime), 'deferred', 'connect to outl...')
#1 /home/script/phpmysqlparser/php-postfix-maillog-importer-master/maillogimporter/parser.php(90): MaillogImporter\Writer\MySql->updateData('B952F19FA96', Array)
#2 /home/script/phpmysqlparser/php-postfix-maillog-importer-master/maillogimporter/parser.php in /home/satish/script/phpmysqlparser/php-postfix-maillog-importer-master/maillogimporter/writer/mysql.php on line 95

**Comment by zewish** [comment]
What's your PHP version?

**Comment by premhunt** [comment]
It is PHP 5.6

**Comment by zewish** [comment]
You don't seem to have a date in this current line of the mail log - that seems to be the problem.

**Comment by juansebas257** [comment]
hi, trying to revive this post i have the same issue, I read carefully the code and the problem is caused for the dateTimeRegex variable in main.php which is not able to decodify correctly the date in the line of the log:

My example:
        'dateTimeRegex' => '^([a-zA-Z]{3} [\d|\s]\d \d{2}\:\d{2}\:\d{2})',
cannot read correctly the date of the line
Aug  5 06:35:24 secure postfix/pickup[2746]: E13F4200460: uid=0 from=<root>

I use php 5.6

How can I modify the datetimeregex for recognize the date format in the current postfix log format?

**Comment by zewish** [comment]
You're missing the year in your date format which is bad for the parser.
What happens when New Year comes and you're parsing the new data?

You have two options here:
1. Change your syslogger configuration to add a year and match the format of the parser;
2. Hack around the maillog parser and add a mapping of month names to numbers after figuring out what the proper regex is... But I wouldn't do that if you're parsing logs collected from different years;

Good luck!
